---
aws:
  region: ap-southeast-2
  resources:
    stack_name: user-aws-resources-stack
    sandpit:
      vpc_id: vpc-2fc3014b
      create_s3_bucket_artifacts: true
      s3_bucket_artifacts: aem-opencloud-artifacts
      route53_public_hostedzone: aemopencloud.space.
      aemopencloud_route53_private_hostedzone: aemopencloud.cms.
      infracatalog_route53_private_hostedzone: infracatalog.srv.
      corp_network_cidr: '1.2.3.4/32'
      # dummy sharing, pointing to Sandpit itself
      share_cmk_aws_account: 918473058104
      forward_proxy_cidr: 10.0.8.0/21
